### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by zaragast**
Adding in the api endpoint our public endpoint from eos impera, the Italian block producer

### CODE REVIEW

**Comment by tarassh** [comment]
Thanks for contributing.

I've just checked the the endpoint, and it seems that history data is not updated. My last two transactions are not visible.

**Comment by eosimpera** [comment]
Sorry, we upgraded our infrastructure in that hour, was a schedule maintenance of our server, now I think everything function

**Comment by tarassh** [comment]
Could you also recompile the node with `-s EOS` flag. Thanks.

**Comment by Amin2110** [comment]
Psy

**Pull request closed without merging**
